export const APP_CONFIG = {
  ESCROW_VENDOR_PERCENTAGE: 80,
  ESCROW_PLATFORM_PERCENTAGE: 20,
  MIN_WITHDRAWAL_AMOUNT: 2000,
  RIDER_MAX_NEGATIVE_BALANCE: -5000,
  TRUST_POINTS_ORDER_COMPLETE: 5,
  TRUST_POINTS_ORDER_CANCEL: -10,
  TRUST_POINTS_RAIN_REPORT: 2,
  RAIN_DELAY_DURATION_MINUTES: 60,
};

export const ORDER_PREFIX = 'QW-';
